<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Michael" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         May 7, 2021 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (preferably HTML) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on the due date. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). You can copy the set-up chunk in Project2.Rmd: I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in our project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is fine as long as you understand what the warnings mean.)</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables (ideally more!) that you want to use to build models/test hypotheses. At least one should be categorical (with 2-5 groups, ideally; definitely fewer than 10) and at least two should be numeric (taking on more than 10 distinct values). Ideally, at least of your variables will be binary (if not, you will have to create one by discretizing a numeric or collapsing levels of a categorical). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, I might encourage you to diversify things a bit and choose a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1 that you want to follow up with). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph. What are they measuring? How many observations?</li>
</ul>
<p>I chose a data set that collected data on Happiness and Alcohol consumption through the variables of Human Development Index, Happiness Score, GDP per Capita, Liters per Capita of Beer Consumed, Liters per Capita of Spirits Consumed, and Liters per Capita of Wine Consumed. These variables were collected by country and each country was classified by the Region and Hemisphere it was in. The data had 122 observations. I wanted to see if there was any correlation between Alcohol consumption and Happiness, as well as if the variables could predict the hemisphere of the earth the country presided in.</p>
<ul>
<li><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all is unreasonable or doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss some of the MANOVA assumptions and whether or not they are likely to have been met here (no need for anything too in-depth) (2).</li>
</ul>
<pre class="r"><code>library(tidyverse)
data &lt;- read.csv(&quot;~/website/content/project/HappinessAlcoholConsumption.csv&quot;)
man &lt;- manova(cbind(HappinessScore, HDI, GDP_PerCapita, Beer_PerCapita, Spirit_PerCapita, Wine_PerCapita)~Hemisphere, data=data)
summary(man)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Hemisphere 1 0.20055 4.8082 6 115 0.0002063 ***
## Residuals 120
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man)</code></pre>
<pre><code>## Response HappinessScore :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 4.651 4.6508 3.6001 0.06018 .
## Residuals 120 155.020 1.2918
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response HDI :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 172168 172168 8.1187 0.005157 **
## Residuals 120 2544749 21206
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response GDP_PerCapita :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 22221 22221 0.5038 0.4792
## Residuals 120 5292420 44103
##
## Response Beer_PerCapita :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 3111 3111.2 0.2815 0.5967
## Residuals 120 1326277 11052.3
##
## Response Spirit_PerCapita :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 69864 69864 11.444 0.000969 ***
## Residuals 120 732567 6105
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Wine_PerCapita :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Hemisphere 1 6145 6144.5 0.7899 0.3759
## Residuals 120 933469 7778.9</code></pre>
<pre class="r"><code>pairwise.t.test(data$HappinessScore, data$Hemisphere, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  data$HappinessScore and data$Hemisphere 
## 
##       north
## south 0.06 
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(data$HDI, data$Hemisphere, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  data$HDI and data$Hemisphere 
## 
##       north 
## south 0.0052
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(data$Spirit_PerCapita, data$Hemisphere, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  data$Spirit_PerCapita and data$Hemisphere 
## 
##       north  
## south 0.00097
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>1 - (0.95 ^ 10)</code></pre>
<pre><code>## [1] 0.4012631</code></pre>
<pre class="r"><code>(0.05/10)</code></pre>
<pre><code>## [1] 0.005</code></pre>
<p>I ran a MANOVA to determine if Hemisphere has an effect on each of the other variables. Of all the variables, three were significant. I ran pairwise t-tests on all three of the variables that were significant, HappinessScore, HDI, and Spirit_PerCapita. It was found that there was a significant difference in HDI and Spirit_PerCapita between countries in the north and south hemispheres.
There were 10 test run, meaning that the probability of at least one type I error would be about 0.4. The adjusted significance level is 0.005. With the new significance level, the difference in Spirit_PerCapita is the only variable still significant.</p>
<pre class="r"><code>ggplot(data, aes(x = HDI, y = Spirit_PerCapita)) +
  geom_point(alpha = .5) + facet_wrap(~Hemisphere)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(data, aes(x = Spirit_PerCapita, y = HappinessScore)) +
  geom_point(alpha = .5) + facet_wrap(~Hemisphere)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(data, aes(x = HappinessScore, y = HDI)) +
  geom_point(alpha = .5) + facet_wrap(~Hemisphere)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-2-3.png" width="768" style="display: block; margin: auto;" />
When running MANOVAs, it is important to maintain the check the assumptions that the data is randomly sampled with independent observations and that the dependent variables is multivariately normal. I graphed out the variables against the hemispheres and it does not look like the data is multivariately normal.</p>
<ul>
<li><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). The statistic can be anything you want (mean difference, correlation, F-statistic/ANOVA, chi-squared), etc. State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</li>
</ul>
<p>Null Hypothesis: The mean happiness score is the same between countries within the northern versus southern hemispheres
Alternative Hypothesis: The mean happiness score is different between countries within the northern versus southern hemispheres</p>
<pre class="r"><code>mean(data[data$Hemisphere == &quot;north&quot;,]$HappinessScore) - mean(data[data$Hemisphere == &quot;south&quot;,]$HappinessScore)</code></pre>
<pre><code>## [1] 0.4767837</code></pre>
<pre class="r"><code>r_dist &lt;- vector()
for (i in 1:5000){
  new &lt;- data.frame(HappinessScore=sample(data$HappinessScore), hemi = data$Hemisphere)
  r_dist[i] &lt;- mean(new[new$hemi==&quot;north&quot;,]$HappinessScore) - mean(new[new$hemi==&quot;south&quot;,]$HappinessScore)
}

mean(r_dist &gt; 0.4767837) * 2</code></pre>
<pre><code>## [1] 0.0628</code></pre>
<p>The randomization test produced a p-value of 0.062, which is greater than 0.05, The concludes that there is not a significant difference in mean happiness score between countries within the northern versus southern hemispheres.</p>
<pre class="r"><code>{hist(r_dist, main=&quot;Randomized Distribution of Mean Differences&quot;, ylab=&quot;&quot;, 
      xlab=&quot;Difference Between North and South Hemispheres&quot;); 
  abline(v=0.4767837, col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" />
The histogram shows that the difference in means is within the histogram which shows that there is a moderate likelihood of there being no difference in means between countries in the northern hemisphere and the southern hemisphere.</p>
<ul>
<li><p><strong>3. (40 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code> using geom_smooth(method=“lm”). If your interaction is numeric by numeric, refer to code in the slides to make the plot or check out the <code>interactions</code> package, which makes this easier. If you have 3 or more predictors, just chose two of them to plot for convenience. (10)</li>
<li>What proportion of the variation in the outcome does your model explain? (4)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (5)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (10)</li>
</ul></li>
</ul>
<pre class="r"><code>library(lmtest)
library(sandwich)
data$Beer_PerCapita_c &lt;- data$Beer_PerCapita - mean(data$Beer_PerCapita)
data$Wine_PerCapita_c &lt;- data$Wine_PerCapita - mean(data$Wine_PerCapita)

linear &lt;- lm(HappinessScore ~ Beer_PerCapita_c * Wine_PerCapita_c, data=data)
summary(linear)</code></pre>
<pre><code>##
## Call:
## lm(formula = HappinessScore ~ Beer_PerCapita_c *
Wine_PerCapita_c,
## data = data)
##
## Residuals:
## Min 1Q Median 3Q Max
## -2.21284 -0.69145 0.06484 0.69003 2.25063
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.542e+00 1.071e-01 51.740 &lt; 2e-16 ***
## Beer_PerCapita_c 3.889e-03 9.841e-04 3.952 0.000132 ***
## Wine_PerCapita_c 3.796e-03 1.263e-03 3.006 0.003237 **
## Beer_PerCapita_c:Wine_PerCapita_c -3.926e-06 1.411e-05
-0.278 0.781275
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 0.9702 on 118 degrees of
freedom
## Multiple R-squared: 0.3044, Adjusted R-squared: 0.2867
## F-statistic: 17.21 on 3 and 118 DF, p-value: 2.453e-09</code></pre>
<p>After running a linear regression, it appears that for every 1 Liter per Capita increase in Beer Consumption the Happiness Score increases by 3.889e-03, for every 1 Liter per Capita increase in Wine Consumption the Happiness Score increases by 3.796e-03. When accounting for the interaction between Wine and Beer consumption, a 1 liter increase in both decreases the Happiness Score by 3.926e-06.</p>
<pre class="r"><code>ggplot(data, aes(x=Beer_PerCapita, y=Wine_PerCapita))+geom_point(aes(color=HappinessScore))+
  geom_smooth(method=&quot;lm&quot;, se=F, fullrange=T, aes(color=HappinessScore))+
  ggtitle(&quot;Wine Per Capita vs. Beer Per Capita&quot;)+ 
xlab(&quot;Beer Per Capita&quot;)+ylab(&quot;Wine Per Capita&quot;)+theme_classic()</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>res &lt;- linear$residuals
shapiro.test(res)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  res
## W = 0.98859, p-value = 0.4045</code></pre>
<pre class="r"><code>bptest(linear)</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  linear
## BP = 1.1838, df = 3, p-value = 0.7569</code></pre>
<p>When running a linear regression, it’s also important to check the assumptions of independent observations, random sampling, normally distributed residuals, and equal variances. From the graph, we can see that the data has a loose linear relationship. We also obtained a p-value of 0.4 (&gt;0.05) from our Shapiro-Wilk normality test, meaning that we must fail to reject the null hypothesis that the data is normal. Finally, from our studentized Breusch-Pagan test we obtained a p-value of 0.76 (&gt; 0.05), which means we must fail to reject the null hypothesis that the data is homoskedasktic.</p>
<pre class="r"><code>coeftest(linear, vcov = vcovHC(linear))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 5.5419e+00 1.0731e-01 51.6428 &lt; 2.2e-16 ***
## Beer_PerCapita_c 3.8893e-03 1.0092e-03 3.8540 0.0001896
***
## Wine_PerCapita_c 3.7960e-03 1.1633e-03 3.2631 0.0014419
**
## Beer_PerCapita_c:Wine_PerCapita_c -3.9262e-06 1.2183e-05
-0.3223 0.7478152
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary(linear)$r.sq</code></pre>
<pre><code>## [1] 0.3043975</code></pre>
<p>I ran the same regression with robust standard errors and found that the p-values for all of the variables decreased slightly, with the exception of only Beer_PerCapita increasing slightly. The same variables were significant in both regressions.
The proportion of variance explained by the model is 0.3044.</p>
<ul>
<li><strong>4. (5 pts)</strong> Rerun same regression model (with the interaction), but this time compute bootstrapped standard errors (either by resampling observations or residuals). Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</li>
</ul>
<pre class="r"><code>sample_dist &lt;- replicate(5000, {
  bootstrapped &lt;- data[sample(nrow(data), replace=TRUE),]
  boot &lt;- lm(HappinessScore ~ Beer_PerCapita_c * Wine_PerCapita_c, data = bootstrapped)
  coef(boot)
})

sample_dist %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>## (Intercept) Beer_PerCapita_c Wine_PerCapita_c
Beer_PerCapita_c:Wine_PerCapita_c
## 1 0.1053459 0.0009736406 0.001179459 1.206227e-05</code></pre>
<p>The bootstrapped standard errors were slightly lower for the intercept, Wine Per Capita,and the interaction between Beer and Wine Per Capita, but slightly higher for Beer Per Capita seperately.</p>
<ul>
<li><p><strong>5. (30 pts)</strong> Fit a logistic regression model predicting a binary variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (5)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), Precision (PPV), and AUC of your model (5)</li>
<li>Using ggplot, make a density plot of the log-odds (logit) colored/grouped by your binary outcome variable (5)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (5)</li>
</ul></li>
</ul>
<pre class="r"><code>class_diag&lt;-function(probs,truth){
  
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]

  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )

  data.frame(acc,sens,spec,ppv,auc)
}</code></pre>
<pre class="r"><code>library(plotROC)
logistic &lt;- glm(Hemisphere ~ Beer_PerCapita + Wine_PerCapita, data = data, family = binomial(link=&quot;logit&quot;))
exp(coeftest(logistic))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)     0.24155    1.45135  0.0221    1.000
## Beer_PerCapita  1.00263    1.00236  3.0481    1.304
## Wine_PerCapita  0.99583    1.00332  0.2837    1.231</code></pre>
<p>For every 1 liter increase of beer consumed per capita, the odds of the country being in the southern hemisphere increases by 1. For every 1 liter increase of wine consumed per capita, the odds of the country being in the southern hemisphere increases by about 0.996.</p>
<pre class="r"><code>data$prob&lt;-predict(logistic,type=&quot;response&quot;)
data$pred&lt;-ifelse(data$prob&gt;0.5,&quot;north&quot;,&quot;south&quot;)
table(prediction=as.numeric(data$prob&gt;.5),truth=data$Hemisphere)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction north south Sum
##        0      96    26 122
##        Sum    96    26 122</code></pre>
<pre class="r"><code>class_diag(data$prob, data$Hemisphere)</code></pre>
<pre><code>##             acc sens spec ppv       auc
## south 0.7868852    0    1 NaN 0.6007612</code></pre>
<pre class="r"><code>data$logpred&lt;-predict(logistic, type=&quot;link&quot;)
data%&gt;%ggplot()+geom_density(aes(logpred,color=Hemisphere,fill=Hemisphere), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+ggtitle(&quot;Density Plot of predicted North vs. South&quot;)+xlab(&quot;predictor (logit)&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROCplot &lt;- ggplot(data) + geom_roc(aes(d = Hemisphere, m = prob), n.cuts = 0)
ROCplot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-11-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6007612</code></pre>
<p>The accuracy of the model is 0.787. The sensitivity of the model is 0. The specificity of the model is 1. The precision of the model is Not a Number. Finally, the AUC of the model is 0.60, which means our model is kind of poor at predicting the hemisphere in which the country resides.</p>
<ul>
<li><p><strong>6. (25 pts)</strong> Perform a logistic regression predicting the same binary response variable from <em>ALL</em> of the rest of your variables (the more, the better!)</p>
<ul>
<li>Fit model, compute in-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, AUC), and interpret (5)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV with the same model and report average out-of-sample classification diagnostics (Accuracy, Sensitivity, Specificity, Precision, and AUC); interpret AUC and compare with the in-sample metrics (10)</li>
<li>Perform LASSO on the same model/variables. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. (5)</li>
<li>Perform 10-fold CV using only the variables lasso selected: compare model’s out-of-sample AUC to that of your logistic regressions above (5)</li>
</ul></li>
</ul>
<pre class="r"><code>library(glmnet)
logistic2 &lt;- glm(Hemisphere ~ HappinessScore + HDI + GDP_PerCapita + Beer_PerCapita + Spirit_PerCapita + Wine_PerCapita, data = data, family = binomial)
exp(coeftest(logistic2))</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##                  Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)      25.44240    6.31012  5.7942    1.082
## HappinessScore    1.20465    1.48440  1.6022    1.892
## HDI               0.99199    1.00405  0.1367    1.048
## GDP_PerCapita     0.99851    1.00133  0.3270    1.302
## Beer_PerCapita    1.01151    1.00381 20.3231    1.003
## Spirit_PerCapita  0.98275    1.00669  0.0736    1.009
## Wine_PerCapita    1.00078    1.00412  1.2076    2.341</code></pre>
<pre class="r"><code>data$prob&lt;-predict(logistic2,type=&quot;response&quot;) 
data$pred&lt;-ifelse(data$prob&gt;0.5,&quot;north&quot;,&quot;south&quot;)

table(prediction=as.numeric(data$prob&gt;.5),truth=data$Hemisphere)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction north south Sum
##        0      91    20 111
##        1       5     6  11
##        Sum    96    26 122</code></pre>
<pre class="r"><code>class_diag(data$prob, data$Hemisphere)</code></pre>
<pre><code>##            acc      sens      spec       ppv       auc
## south 0.795082 0.2307692 0.9479167 0.5454545 0.8108974</code></pre>
<p>I ran a logistic regression predicting hemisphere from the rest of my variables. I found that for every one unit increase in the happiness score the odds of the country residing in the southern hemisphere increased by 1.2. When HDI increased by one unit, the odds of the country residing in the southern hemisphere increased by 0.99. When GDP_PerCapita increased by one unit, the odds of the country residing in the southern hemisphere increased by 0.99, as well. When Beer_PerCapita, the odds of the country residing in the southern hemisphere increased by 1.0. When Spirit_PerCapita increased by one unit, the odds of the country residing in the southern hemisphere increased by 0.98. Finally, a one unit increase in Wine_PerCapita caused the odds of the country residing in the southern hemisphere to increase by 1.0.
The accuracy for the mode was about 0.8. The sensitivity was about 0.23 for the model. The specificity was about 0.95 for the model. The precision for the model was about 0.54. Finally, the AUC for the model was 0.81, which means our model is a fair predictor of hemisphere.</p>
<pre class="r"><code>set.seed(1234)
k=10 

data1&lt;-data[sample(nrow(data)),]
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$Hemisphere
 fit&lt;-glm(Hemisphere~HappinessScore + HDI + GDP_PerCapita + Beer_PerCapita + Spirit_PerCapita + Wine_PerCapita, data=train, family=binomial(link=&quot;logit&quot;))
 probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)</code></pre>
<pre><code>##         acc      sens      spec ppv       auc
## 1 0.7878205 0.3083333 0.9340404 NaN 0.7892782</code></pre>
<p>After running a k-fold CV, I found that the accuracy of the model was about 0.787, the sensitivity of the model was about 0.31, the specificity was about 0.93, the precision was not a number, and finally the AUG was bout 0.79, which was a light decrease from the original regression.</p>
<pre class="r"><code>mat&lt;-model.matrix(logistic2)
y&lt;-as.matrix(data$Hemisphere)
x&lt;-as.data.frame(mat) %&gt;% dplyr::select(-1) %&gt;% as.matrix
cv&lt;-cv.glmnet(x,y, family = &quot;binomial&quot;)
lasso&lt;-glmnet(x,y, family = &quot;binomial&quot;,lambda=cv$lambda.1se)

coef(lasso)</code></pre>
<pre><code>## 7 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                             s0
## (Intercept)      -0.3560076133
## HappinessScore    .           
## HDI              -0.0007504704
## GDP_PerCapita     .           
## Beer_PerCapita    .           
## Spirit_PerCapita -0.0046198490
## Wine_PerCapita    .</code></pre>
<p>After running a LASSO on the regression, it was found that the two variables that are the best predictors of hemisphere were HDI and Spirit_PerCapita.</p>
<pre class="r"><code>set.seed(1234)
k=10 

data1&lt;-data[sample(nrow(data)),]
folds&lt;-cut(seq(1:nrow(data)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
 train&lt;-data1[folds!=i,]
 test&lt;-data1[folds==i,]
 truth&lt;-test$Hemisphere
 fit&lt;-glm(Hemisphere~HDI + Spirit_PerCapita, data=train, family=binomial(link=&quot;logit&quot;))
 probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)
 diags&lt;-rbind(diags,class_diag(probs,truth))
}

summarize_all(diags,mean)</code></pre>
<pre><code>##         acc sens      spec ppv       auc
## 1 0.7538462    0 0.9614646 NaN 0.7254672</code></pre>
<p>Finally, I ran another k-fold CV and found that the accuracy was slightly lower in this model with a value of 0.754. The sensitivity of the model was 0, the specificity of the model was 0.96, the precision of the model was not a number, and finally the AUC was about 0.73, which is a decrease from the original model.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
